project:
  type: book
  resources:
    - cover.png
    - cover.tex
    - preamble.tex

lang: pt-BR

book:
  title: "Formação Definitiva do Arquiteto de Software .NET"
  subtitle: "Construindo Sistemas Financeiros de Alta Performance"
  author: "Jeffreys Sharp"
  date: today
  chapters:
    - index.qmd
    - chapters/part1-vision/01-purpose.qmd
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-depth: 3

  pdf:
    pdf-engine: lualatex
    documentclass: book
    titlepage: false
    fontsize: 11pt
    linestretch: 1.18
    number-sections: true
    highlight-style: github
    include-in-header:
      - preamble.tex
    toc: true
    toc-depth: 3
    toc-title: "Sumário"

    lof: true
    lof-title: "Lista de Figuras"

    lot: true
    lot-title: "Lista de Tabelas"

    classoption:
      - oneside
      - openany

    geometry:
      - paperwidth=6in
      - paperheight=9in
      - top=2.2cm
      - bottom=2.2cm
      - inner=2.5cm
      - outer=2.0cm

  epub:
    toc: true
    toc-depth: 3